PROJ-KINO/KINO-FE

src/components/Header.tsx

FEAT : 헤더 구현

---

package-lock.json
package.json
src/App.css
src/App.tsx
src/pages/Main.tsx
src/styles/GlobalStyle.ts
yarn.lock

FEAT : 메인페이지 구현

---

src/components/TagSelector.tsx

버튼 작게
정렬 맞추기
> ex) #이슈번호, #이슈번호
- close #17
> 주문하신 버튼 작게 / 정렬 맞추기
> 리뷰어가 특별히 봐주었으면 하는 부분이나 다른 팀원들이 알아야할 사항이 있다면 작성해주세요
>
> 이 정도면 되었을까요?

fix: 오윤 님께

---

src/components/AdminModal.tsx

> ex) #이슈번호, #이슈번호
- close #24 
- 모바일 환경에서 발생하는 어드민 페이지 버그 수정

FIX : 어드민 모달 버그 수정

---

src/components/AdminList.tsx
src/components/AdminModal.tsx
src/components/ConfirmDialog.tsx
src/pages/Admin.tsx
src/styles/theme.ts

- close #26 
- 공통 모달 구현
- 어드민 반응형 에러 수정

FEAT: 공통 모달 구현

---

src/App.tsx
src/components/AdminModal.tsx
src/components/ReportModal.tsx

- close #29 
- 신고 모달 구현
- 기존 신고 모달 버그 수정
부모 컴포넌트에서 isModalOpen 상태를 만든 후 모달의 props로 setIsModalOpen을 전달하여 사용합니다.
이해 안되시면 연락주세요.

FEAT : 신고 모달 구현

---

src/App.tsx
src/components/AdminList.tsx
src/components/AdminModal.tsx
src/hooks/useFormatDate.ts
src/pages/Admin.tsx

- #28 
- 어드민 페이지 API 연동 마무리 중입니다.
- 페이지네이션과 무한 스크롤 구현 예정입니다.💩

FEAT : 어드민 페이지 API 연동

---

tsconfig.app.json

- close #34 
- 사용하지 않는 파라미터도 빌드 시 허용
없습니다.

CHORE : 빌드 파일 수정

---

src/App.tsx

ThemeProvider 하나로
> #37 
- close #37
> 머지할 때 잘못 넣었던 테마 프로바이더 태그를 정리했어요.
> 딱히 ..

fix: app.tsx

---

src/App.tsx
src/components/MovieInfo.tsx

> ex) #39
- close #39
> 영화 상세 정보 - 프로바이더 인터페이스 추가
> 로컬에서 돌리면 돌아가는데 왜 배포할 때는 에러가 날까요?

Fix: 프로바이더 인터페이스 추가

---

src/components/mypage/ReviewCard.tsx

DetailReview 인터페이스에서 리뷰어는 필수
> ex) #41 
- close #41
> 디테일리뷰 인터페이스에서 리뷰어 필수
> 빨간줄을 간과하지 말자...

fix: 리뷰 카드

---

src/components/mypage/DetailReviewCard.tsx
src/components/mypage/ReviewCard.tsx
src/pages/mypage/MyPageMain.tsx

빨간줄을 무시하지 말자..
> ex) #43
- close #43
> 애초에 잘 맞추자...
> 아자아자 파이팅^^

fix: 디테일 리뷰 인터페이스 깔맞춤

---

src/App.tsx
src/components/Header.tsx
src/components/MainHeader.tsx

- #51 
- 헤더 라우팅 설정
- 헤더 렌더링 지연 버그 수정 ( 어드민 페이지에서 라이트/다크 모드를 지원하는 페이지 이동 시 헤더 리렌더링 지연) 
없습니다. 모두 화이팅

FEAT : 헤더 라우팅 설정

---

package-lock.json
package.json
src/api/mypage.ts
src/components/mypage/DetailReviewCard.tsx
src/components/mypage/MovieCard.tsx
src/components/mypage/ReviewCard.tsx
src/components/mypage/SettingForm.tsx
src/components/mypage/TagSelectionForm.tsx
src/components/mypage/UserProfileSection.tsx
src/pages/mypage/MyFavoriteMoviesPage.tsx
src/pages/mypage/MyPageMain.tsx
src/pages/mypage/MyReviewsDetailPage.tsx
src/pages/mypage/MyReviewsShortPage.tsx
src/pages/mypage/MySettingsPage.tsx
src/pages/mypage/MyTagsPage.tsx
yarn.lock

FEAT : 마이페이지 API 연동

---

src/components/Review.tsx
src/components/mypage/DetailReviewCard.tsx
src/pages/mypage/MyPageMain.tsx
src/pages/mypage/MyReviewsDetailPage.tsx

> ex) #70
- close #70
>  타입 맞추기...
> 앞으로 그러지 말자 ^^

Fix: 빌드 에러 해결

---

src/App.tsx
src/api/AxiosInstance.ts
src/components/ConfirmDialog.tsx
src/components/GoogleCallback.tsx
src/components/KakaoCallback.tsx
src/components/MainConfirmDialog.tsx
src/components/MainHeader.tsx
src/components/NaverCallback.tsx
src/context/DialogContext.tsx

- close #72 
- 헤더 로그아웃 확인 모달 추가
- 토큰 만료시 로그인 알림 모달 추가
- 서버 에러 시 사용자 알림 모달 추가
얼마 안남았심더. 🔥화이팅🔥

FEAT : 모달 처리

---

src/api/AxiosInstance.ts
src/components/MainHeader.tsx
src/components/SearchBar.tsx
src/pages/Main.tsx

- #63 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요
- 메인화면 UI 개선중입니다.
- 지속적으로 개선할 예정입니다.

DESIGN : 메인화면 UI 개선

---

src/components/GoogleCallback.tsx
src/components/KakaoCallback.tsx
src/components/NaverCallback.tsx

FIX : 로그인 라우팅 수정

---

src/assets/svg/KinoLogoPlaceholder.tsx
src/assets/svg/KinoPosterPlaceholder.tsx
src/components/Header.tsx
src/components/MainHeader.tsx
src/pages/Main.tsx

- #63 
- ck에디터로 작성된 html 파일 렌더링
없습니다.

FEAT : 리뷰 HTML 렌더링

---

src/api/AxiosInstance.ts
src/api/details.ts
src/components/GeneralMovieInfo.tsx
src/components/MovieInfo.tsx
src/pages/mypage/MyPageMain.tsx

아이디는 넘버시다
> ex) #86
- close #86
> 타입 에러
> 아이디는 넘버
> 아이디는 넘버
>

fix: 타입 에러

---

src/components/GeneralMovieInfo.tsx
src/pages/MovieDetail.tsx

> ex) #86
- close #86
> 찜 기능 구현
> genres -> genreId 아이디 배열로 받기로 함
>

feat: zzim

---

src/components/Review.tsx
src/components/ShortReview.tsx
src/components/community/Comment.tsx
src/components/mypage/DetailReviewCard.tsx
src/lang/translation.en.json
src/lang/translation.ko.json
src/pages/MovieDetail.tsx
src/pages/community/CommunityDetailPage.tsx
src/pages/community/CommunityListPage.tsx

> ex) #90
- close #90
> 유저 처리 - 글쓰기, 댓글 쓰기 막음
> 게시글 처리 - 안 보이게 막음:
> 힘냅시다^^

feat: 제재 처리

---

package-lock.json
package.json

> ex) #96
- close #
> i18next 패키지 설치
>

Fix: 빌드 에러

---

src/App.tsx
src/api/admin.ts
src/api/details.ts
src/api/home.ts
src/api/movie.ts
src/api/reviews.ts
src/components/admin/AdminChart.tsx
src/components/admin/AdminList.tsx
src/components/mypage/DetailReviewCard.tsx
tsconfig.app.json

- close #109
> build error
> 
^^

fix: build error

---

src/components/mypage/DetailReviewCard.tsx
src/components/mypage/MovieCard.tsx
src/components/mypage/UserProfileSection.tsx
src/lang/translation.en.json
src/lang/translation.ko.json
src/pages/community/CommunityDetailPage.tsx
src/pages/mypage/MyPageMain.tsx

> ex) #120 
> 모달이랑
> 이것저것 완성도를...
>

Fix/#112 최최종

---

src/components/ShortReview.tsx
src/components/mypage/DetailReviewCard.tsx
src/lang/translation.en.json
src/lang/translation.ko.json

- close #128
> 경로
> 번역 제이슨 에러
> 리뷰어가 특별히 봐주었으면 하는 부분이나 다른 팀원들이 알아야할 사항이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

fix: 경로 건들면 죽는다
